sys_includes = ["sys/user.h"]
include_guard = "_SYS_PROCFS_H"
language = "C"
style = "Tag"

[enum]
prefix_with_name = true

[export]
include = [
    "psaddr_t",
    "prgregset_t",
    "prfpregset_t",
    "lwpid_t",
    "prstatus_t",
    "prpsinfo_t",
]
