sys_includes = []
include_guard = "_AARCH64_USER_H"
language = "C"
style = "Tag"

[enum]
prefix_with_name = true

[export]
include = [
    "user_regs_struct",
    "user_fpsimd_struct",
    "elf_gregset_t",
    "elf_greg_t",
    "elf_fpregset_t",
]
